package org.lucee.lucli.server.runtime;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.lucee.lucli.server.LuceeServerConfig;
import org.lucee.lucli.server.TomcatConfigSupport;

/**
 * Generates a minimal JETTY_BASE directory structure suitable for use with
 * any JETTY_HOME — an external Jetty distribution installation.
 *
 * The generated JETTY_BASE contains:
 * - start.d/*.ini   — module configuration (http port, server, deploy, jvm args)
 * - webapps/root.xml — Jetty context XML descriptor pointing to the project webroot
 * - etc/lucee-web.xml — web.xml with Lucee servlet registration
 * - lib/ext/         — Lucee JAR
 * - resources/       — Jetty logging properties
 * - lucee-server/, lucee-web/ — Lucee contexts
 * - logs/, tmp/
 *
 * The project webroot stays clean — all configuration lives at the server level.
 */
public class JettyBaseConfigGenerator {

    /**
     * Generate JETTY_BASE configuration from a JETTY_HOME.
     *
     * @param jettyBase         The JETTY_BASE directory (~/.lucli/servers/&lt;name&gt;)
     * @param config            Server configuration from lucee.json
     * @param projectDir        Project directory
     * @param jettyHome         Jetty installation directory
     * @param jettyMajorVersion Major version of Jetty (e.g. 11, 12). Use 0 when unknown.
     * @param stopPort          Port for graceful shutdown (STOP.PORT)
     * @param stopKey           Key for graceful shutdown (STOP.KEY)
     */
    public void generateConfiguration(Path jettyBase, LuceeServerConfig.ServerConfig config,
                                      Path projectDir, Path jettyHome,
                                      int jettyMajorVersion,
                                      int stopPort, String stopKey) throws IOException {

        // Create JETTY_BASE directory structure
        createJettyBaseStructure(jettyBase);

        // Generate start.d/*.ini module configuration files
        generateStartIniFiles(jettyBase, config, jettyMajorVersion, stopPort, stopKey);

        // Generate JVM options ini (memory, system properties)
        generateJvmIni(jettyBase, config, projectDir);

        // Generate Jetty context XML descriptor for the project webroot
        generateContextXml(jettyBase, config, projectDir);

        // Generate web.xml with Lucee servlet registration
        generateLuceeWebXml(jettyBase, config);

        // Generate logging properties
        generateLoggingProperties(jettyBase);
    }

    /**
     * Create the JETTY_BASE directory structure.
     */
    private void createJettyBaseStructure(Path jettyBase) throws IOException {
        Files.createDirectories(jettyBase.resolve("start.d"));
        Files.createDirectories(jettyBase.resolve("webapps"));
        Files.createDirectories(jettyBase.resolve("lib/ext"));
        Files.createDirectories(jettyBase.resolve("etc"));
        Files.createDirectories(jettyBase.resolve("resources"));
        Files.createDirectories(jettyBase.resolve("logs"));
        Files.createDirectories(jettyBase.resolve("tmp"));
        Files.createDirectories(jettyBase.resolve("lucee-server"));
        Files.createDirectories(jettyBase.resolve("lucee-web"));
    }

    /**
     * Generate start.d/*.ini files for Jetty module configuration.
     */
    private void generateStartIniFiles(Path jettyBase, LuceeServerConfig.ServerConfig config,
                                       int jettyMajorVersion, int stopPort, String stopKey) throws IOException {
        Path startD = jettyBase.resolve("start.d");

        // server.ini — base server module
        StringBuilder serverIni = new StringBuilder();
        serverIni.append("# Auto-generated by LuCLI\n");
        serverIni.append("--module=server\n");
        serverIni.append("jetty.server.stopAtShutdown=true\n");
        Files.writeString(startD.resolve("server.ini"), serverIni.toString(), StandardCharsets.UTF_8);

        // http.ini — HTTP connector with configured port
        StringBuilder httpIni = new StringBuilder();
        httpIni.append("# Auto-generated by LuCLI\n");
        httpIni.append("--module=http\n");
        httpIni.append("jetty.http.port=").append(config.port).append("\n");
        String bind = LuceeServerConfig.getEffectiveBindAddress(config);
        httpIni.append("jetty.http.host=").append("*".equals(bind) ? "0.0.0.0" : bind).append("\n");
        Files.writeString(startD.resolve("http.ini"), httpIni.toString(), StandardCharsets.UTF_8);

        // deploy.ini — web application deployment scanning
        // Jetty 12 uses environment-specific deploy modules (ee8-deploy, ee10-deploy)
        // Jetty 11 and below use the simple deploy module
        StringBuilder deployIni = new StringBuilder();
        deployIni.append("# Auto-generated by LuCLI\n");
        if (jettyMajorVersion >= 12) {
            deployIni.append("--module=ee10-deploy\n");
        } else {
            deployIni.append("--module=deploy\n");
        }
        Files.writeString(startD.resolve("deploy.ini"), deployIni.toString(), StandardCharsets.UTF_8);

        // ext.ini — enable ext module so lib/ext/ JARs are on the classpath
        StringBuilder extIni = new StringBuilder();
        extIni.append("# Auto-generated by LuCLI\n");
        extIni.append("--module=ext\n");
        Files.writeString(startD.resolve("ext.ini"), extIni.toString(), StandardCharsets.UTF_8);

        // stop.ini — graceful shutdown configuration
        StringBuilder stopIni = new StringBuilder();
        stopIni.append("# Auto-generated by LuCLI\n");
        stopIni.append("STOP.PORT=").append(stopPort).append("\n");
        stopIni.append("STOP.KEY=").append(stopKey).append("\n");
        Files.writeString(startD.resolve("stop.ini"), stopIni.toString(), StandardCharsets.UTF_8);

        // requestlog.ini — enable request logging to logs/
        StringBuilder requestLogIni = new StringBuilder();
        requestLogIni.append("# Auto-generated by LuCLI\n");
        requestLogIni.append("--module=requestlog\n");
        Files.writeString(startD.resolve("requestlog.ini"), requestLogIni.toString(), StandardCharsets.UTF_8);
    }

    /**
     * Generate jvm.ini with memory settings and system properties.
     */
    private void generateJvmIni(Path jettyBase, LuceeServerConfig.ServerConfig config,
                                Path projectDir) throws IOException {
        Path startD = jettyBase.resolve("start.d");

        StringBuilder jvmIni = new StringBuilder();
        jvmIni.append("# Auto-generated by LuCLI\n");
        jvmIni.append("--exec\n");

        // Memory settings
        jvmIni.append("-Xms").append(config.jvm.minMemory).append("\n");
        jvmIni.append("-Xmx").append(config.jvm.maxMemory).append("\n");

        // Lucee context paths
        Path luceeServerRoot = jettyBase.resolve("lucee-server");
        Path luceeWebRoot = jettyBase.resolve("lucee-web");
        jvmIni.append("-Dlucee.server.dir=").append(luceeServerRoot.toAbsolutePath()).append("\n");
        jvmIni.append("-Dlucee.web.dir=").append(luceeWebRoot.toAbsolutePath()).append("\n");

        // Temp directory
        jvmIni.append("-Djava.io.tmpdir=").append(jettyBase.resolve("tmp").toAbsolutePath()).append("\n");

        // JMX configuration if monitoring is enabled
        if (config.monitoring != null && config.monitoring.enabled && config.monitoring.jmx != null) {
            jvmIni.append("-Dcom.sun.management.jmxremote\n");
            jvmIni.append("-Dcom.sun.management.jmxremote.port=").append(config.monitoring.jmx.port).append("\n");
            jvmIni.append("-Dcom.sun.management.jmxremote.authenticate=false\n");
            jvmIni.append("-Dcom.sun.management.jmxremote.ssl=false\n");
        }

        // Additional JVM args from lucee.json
        if (config.jvm.additionalArgs != null) {
            for (String arg : config.jvm.additionalArgs) {
                if (arg != null && !arg.trim().isEmpty()) {
                    jvmIni.append(arg.trim()).append("\n");
                }
            }
        }

        Files.writeString(startD.resolve("jvm.ini"), jvmIni.toString(), StandardCharsets.UTF_8);
    }

    /**
     * Generate Jetty context XML descriptor that points to the project webroot.
     *
     * For Jetty 12, uses ee10 WebAppContext. For older versions, uses the
     * standard WebAppContext.
     */
    private void generateContextXml(Path jettyBase, LuceeServerConfig.ServerConfig config,
                                    Path projectDir) throws IOException {
        Path webroot = LuceeServerConfig.resolveWebroot(config, projectDir);
        Path luceeWebXml = jettyBase.resolve("etc/lucee-web.xml");

        // Determine the WebAppContext class based on what's available.
        // Jetty 12 uses org.eclipse.jetty.ee10.webapp.WebAppContext
        // Jetty 11 and below use org.eclipse.jetty.webapp.WebAppContext
        // We use ee10 as default since Lucee 7 targets jakarta.servlet (Jetty 12)
        // and fall back gracefully.
        String webAppContextClass = "org.eclipse.jetty.ee10.webapp.WebAppContext";

        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<!DOCTYPE Configure PUBLIC \"-//Jetty//Configure//EN\" \"https://jetty.org/configure_10_0.dtd\">\n");
        xml.append("<Configure class=\"").append(webAppContextClass).append("\">\n");
        xml.append("  <Set name=\"contextPath\">/</Set>\n");
        xml.append("  <Set name=\"resourceBase\">").append(webroot.toAbsolutePath()).append("</Set>\n");
        xml.append("  <Set name=\"descriptor\">").append(luceeWebXml.toAbsolutePath()).append("</Set>\n");
        xml.append("  <Set name=\"extractWAR\">false</Set>\n");
        xml.append("  <Set name=\"copyWebDir\">false</Set>\n");
        xml.append("  <Set name=\"parentLoaderPriority\">true</Set>\n");

        // Add extra classpath for Lucee JARs in lib/ext/
        xml.append("  <Set name=\"extraClasspath\">").append(jettyBase.resolve("lib/ext").toAbsolutePath()).append("</Set>\n");

        xml.append("</Configure>\n");

        Files.writeString(jettyBase.resolve("webapps/root.xml"), xml.toString(), StandardCharsets.UTF_8);
    }

    /**
     * Generate web.xml with Lucee servlet registration for the Jetty context.
     *
     * This is placed in JETTY_BASE/etc/lucee-web.xml and referenced by the
     * context XML descriptor.
     */
    private void generateLuceeWebXml(Path jettyBase, LuceeServerConfig.ServerConfig config) throws IOException {
        Path luceeServerRoot = jettyBase.resolve("lucee-server");
        Path luceeWebRoot = jettyBase.resolve("lucee-web");

        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<web-app xmlns=\"https://jakarta.ee/xml/ns/jakartaee\"\n");
        xml.append("         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n");
        xml.append("         xsi:schemaLocation=\"https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd\"\n");
        xml.append("         metadata-complete=\"true\"\n");
        xml.append("         version=\"6.0\">\n\n");

        xml.append("  <request-character-encoding>UTF-8</request-character-encoding>\n");
        xml.append("  <response-character-encoding>UTF-8</response-character-encoding>\n\n");

        if (config.enableLucee) {
            // CFMLServlet
            xml.append("  <!-- Lucee CFML Servlet -->\n");
            xml.append("  <servlet>\n");
            xml.append("    <servlet-name>CFMLServlet</servlet-name>\n");
            xml.append("    <servlet-class>lucee.loader.servlet.jakarta.CFMLServlet</servlet-class>\n");
            xml.append("    <init-param>\n");
            xml.append("      <param-name>lucee-server-root</param-name>\n");
            xml.append("      <param-value>").append(luceeServerRoot.toAbsolutePath()).append("</param-value>\n");
            xml.append("    </init-param>\n");
            xml.append("    <init-param>\n");
            xml.append("      <param-name>lucee-web-root</param-name>\n");
            xml.append("      <param-value>").append(luceeWebRoot.toAbsolutePath()).append("</param-value>\n");
            xml.append("    </init-param>\n");
            xml.append("    <load-on-startup>1</load-on-startup>\n");
            xml.append("  </servlet>\n\n");

            // CFML servlet mappings
            String[] cfmlPatterns = {"*.cfm", "*.cfml", "*.cfc", "*.cfs", "/index.cfm/*", "/lucee/admin.cfm"};
            for (String pattern : cfmlPatterns) {
                xml.append("  <servlet-mapping>\n");
                xml.append("    <servlet-name>CFMLServlet</servlet-name>\n");
                xml.append("    <url-pattern>").append(pattern).append("</url-pattern>\n");
                xml.append("  </servlet-mapping>\n");
            }
            xml.append("\n");

            // RESTServlet (if enabled)
            if (config.enableREST) {
                xml.append("  <!-- Lucee REST Servlet -->\n");
                xml.append("  <servlet>\n");
                xml.append("    <servlet-name>RESTServlet</servlet-name>\n");
                xml.append("    <servlet-class>lucee.loader.servlet.jakarta.RestServlet</servlet-class>\n");
                xml.append("    <load-on-startup>2</load-on-startup>\n");
                xml.append("  </servlet>\n");
                xml.append("  <servlet-mapping>\n");
                xml.append("    <servlet-name>RESTServlet</servlet-name>\n");
                xml.append("    <url-pattern>/rest/*</url-pattern>\n");
                xml.append("  </servlet-mapping>\n\n");
            }

            // Welcome files
            xml.append("  <welcome-file-list>\n");
            xml.append("    <welcome-file>index.cfm</welcome-file>\n");
            xml.append("    <welcome-file>index.cfml</welcome-file>\n");
            xml.append("    <welcome-file>index.html</welcome-file>\n");
            xml.append("  </welcome-file-list>\n\n");

            // Protect lucee.json from being served
            xml.append("  <!-- Protect lucee.json from being served -->\n");
            xml.append("  <security-constraint>\n");
            xml.append("    <web-resource-collection>\n");
            xml.append("      <web-resource-name>Lucee Config</web-resource-name>\n");
            xml.append("      <url-pattern>/lucee.json</url-pattern>\n");
            xml.append("      <url-pattern>/lucee-lock.json</url-pattern>\n");
            xml.append("    </web-resource-collection>\n");
            xml.append("    <auth-constraint/>\n");
            xml.append("  </security-constraint>\n");
        } else {
            // Static server — just serve files, no Lucee
            xml.append("  <welcome-file-list>\n");
            xml.append("    <welcome-file>index.html</welcome-file>\n");
            xml.append("    <welcome-file>index.htm</welcome-file>\n");
            xml.append("  </welcome-file-list>\n");
        }

        xml.append("\n</web-app>\n");

        Files.writeString(jettyBase.resolve("etc/lucee-web.xml"), xml.toString(), StandardCharsets.UTF_8);
    }

    /**
     * Generate Jetty logging configuration.
     */
    private void generateLoggingProperties(Path jettyBase) throws IOException {
        StringBuilder props = new StringBuilder();
        props.append("# Auto-generated by LuCLI\n");
        props.append("org.eclipse.jetty.LEVEL=INFO\n");
        props.append("org.eclipse.jetty.server.LEVEL=INFO\n");
        props.append("org.eclipse.jetty.io.LEVEL=WARN\n");

        Files.writeString(jettyBase.resolve("resources/jetty-logging.properties"),
                props.toString(), StandardCharsets.UTF_8);
    }

    /**
     * Deploy the Lucee JAR to the JETTY_BASE lib/ext/ directory.
     */
    public void deployLuceeJar(Path luceeJar, Path jettyBase, String version, String variant)
            throws IOException {
        Path extDir = jettyBase.resolve("lib/ext");
        Files.createDirectories(extDir);

        String jarName = "standard".equals(variant)
                ? "lucee-" + version + ".jar"
                : "lucee-" + variant + "-" + version + ".jar";
        Path targetJar = extDir.resolve(jarName);

        if (Files.exists(targetJar)) {
            System.out.println("Lucee JAR already deployed: " + targetJar);
            return;
        }

        System.out.println("Deploying Lucee JAR to JETTY_BASE: " + targetJar);
        Files.copy(luceeJar, targetJar, StandardCopyOption.REPLACE_EXISTING);
    }
}
